[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true

[project]
name = "repogenie"
version = "0.2.2"
description = "AI assistant for repository understanding and docs"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GNU AFFERO GENERAL PUBLIC LICENSE"}
authors = [
  {name = "Shubham Raj", email = "shubhhu.raj@gmail.com"}
]

dependencies = [
    "click",
    "pathspec>=1.0.3",
    "pyyaml",
    "rich",
    "python-dotenv",
    "groq>=1.1.1"
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "twine>=6.2.0",
]

[project.urls]
Repository = "https://github.com/shubhutf/RepoGenie"
Issues = "https://github.com/shubhutf/RepoGenie/issues"

[project.scripts]
repogenie  = "doclify.pipelines.supervisor:cli"

[tool.setuptools]
[tool.setuptools.packages.find]
where = ["."]
include = ["doclify*"]

[tool.setuptools.package-data]
"doclify" = ["resources/*.gitignore"]